import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateReport(stats, transactions, companyName) {
  try {
    const doc  = new jsPDF();
    const name = companyName || 'LedgerFlow';
    const date = new Date().toLocaleDateString('en-US', {
      year:'numeric', month:'long', day:'numeric',
    });

    // ── Header ────────────────────────────────────────────────
    doc.setFontSize(24);
    doc.setTextColor(10, 185, 138);
    doc.text(name, 14, 20);

    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text('Financial Report', 14, 28);
    doc.text(`Generated: ${date}`, 14, 34);

    // ── Divider line ──────────────────────────────────────────
    doc.setDrawColor(226, 232, 240);
    doc.line(14, 38, 196, 38);

    // ── Summary stats ─────────────────────────────────────────
    const totalRevenue   = Number(stats?.total_revenue  || 0);
    const totalExpenses  = Number(stats?.total_expenses || 0);
    const netProfit      = totalRevenue - totalExpenses;
    const docsProcessed  = Number(stats?.docs_processed || 0);
    const uncategorized  = Number(stats?.uncategorized  || 0);

    const fmt = (n) =>
      `$${Math.abs(n).toLocaleString('en', { minimumFractionDigits:2, maximumFractionDigits:2 })}`;

    autoTable(doc, {
      startY:     44,
      head:       [['Financial Summary', 'Amount']],
      body:       [
        ['Total Revenue',          fmt(totalRevenue)  ],
        ['Total Expenses',         fmt(totalExpenses) ],
        ['Net Profit',             fmt(netProfit)     ],
        ['Documents Processed',    docsProcessed.toString()],
        ['Uncategorized Transactions', uncategorized.toString()],
      ],
      styles:      { fontSize:11, cellPadding:6 },
      headStyles:  {
        fillColor:  [10, 185, 138],
        textColor:  255,
        fontStyle:  'bold',
      },
      alternateRowStyles: { fillColor:[248, 250, 252] },
      columnStyles: { 1: { halign:'right', fontStyle:'bold' } },
    });

    // ── Expense breakdown ─────────────────────────────────────
    if (stats?.expense_breakdown?.length > 0) {
      const afterSummary = doc.lastAutoTable.finalY + 12;

      doc.setFontSize(13);
      doc.setTextColor(15, 23, 42);
      doc.text('Expense Breakdown by Category', 14, afterSummary);

      const breakdownRows = stats.expense_breakdown.map(b => [
        b.category || 'Uncategorized',
        fmt(b.total),
        `${((b.total / totalExpenses) * 100).toFixed(1)}%`,
      ]);

      autoTable(doc, {
        startY:     afterSummary + 4,
        head:       [['Category', 'Amount', '% of Total']],
        body:       breakdownRows,
        styles:     { fontSize:10, cellPadding:5 },
        headStyles: {
          fillColor: [15, 23, 42],
          textColor: 255,
          fontStyle: 'bold',
        },
        alternateRowStyles: { fillColor:[248, 250, 252] },
        columnStyles: {
          1: { halign:'right' },
          2: { halign:'right' },
        },
      });
    }

    // ── Transactions table ────────────────────────────────────
    if (transactions && transactions.length > 0) {
      const afterBreakdown = doc.lastAutoTable.finalY + 12;

      doc.setFontSize(13);
      doc.setTextColor(15, 23, 42);
      doc.text('Transaction History', 14, afterBreakdown);

      const txnRows = transactions.slice(0, 100).map(t => [
        t.txn_date                              || '—',
        t.vendor                                || '—',
        t.category || t.ml_category            || 'Uncategorized',
        t.txn_type === 'income' ? 'Income'      : 'Expense',
        fmt(Math.abs(t.amount || 0)),
      ]);

      autoTable(doc, {
        startY:     afterBreakdown + 4,
        head:       [['Date','Vendor','Category','Type','Amount']],
        body:       txnRows,
        styles:     { fontSize:9, cellPadding:4 },
        headStyles: {
          fillColor: [10, 185, 138],
          textColor: 255,
          fontStyle: 'bold',
        },
        alternateRowStyles: { fillColor:[248, 250, 252] },
        columnStyles: {
          4: { halign:'right', fontStyle:'bold' },
        },
      });
    }

    // ── Footer on every page ──────────────────────────────────
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `${name} — Financial Report — Page ${i} of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 10,
      );
      doc.text(
        'Generated by LedgerFlow | This report is for informational purposes only',
        14,
        doc.internal.pageSize.height - 6,
      );
    }

    // ── Save ──────────────────────────────────────────────────
    const fileName = `${name.replace(/\s+/g, '_')}_Report_${new Date().getFullYear()}.pdf`;
    doc.save(fileName);
    return true;

  } catch (err) {
    console.error('PDF generation error:', err);
    alert(`Could not generate PDF: ${err.message}`);
    return false;
  }
}