"""add all missing columns

Revision ID: 0716ec1e1d49
Revises: 
Create Date: 2026-04-19 13:41:10.937692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0716ec1e1d49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_logs', sa.Column('document_id', sa.String(), nullable=True))
    op.add_column('agent_logs', sa.Column('agent', sa.String(), nullable=True))
    op.alter_column('agent_logs', 'action',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('agent_logs', 'status',
               existing_type=postgresql.ENUM('RUNNING', 'DONE', 'FAILED', 'WAITING', name='agentstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('agent_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('agent_logs_related_doc_fkey', 'agent_logs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_logs', 'documents', ['document_id'], ['id'])
    op.drop_column('agent_logs', 'log_metadata')
    op.drop_column('agent_logs', 'related_doc')
    op.drop_column('agent_logs', 'finished_at')
    op.drop_column('agent_logs', 'agent_name')
    op.add_column('budgets', sa.Column('spent', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('remaining', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('status', sa.String(), nullable=True))
    op.add_column('budgets', sa.Column('alert_at_pct', sa.Float(), nullable=True))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=True))
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'REVIEW', name='documentstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('documents', 'ai_notes')
    op.drop_column('documents', 'vendor_address')
    op.drop_column('documents', 'raw_text')
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'line_items')
    op.drop_column('documents', 's3_key')
    op.drop_column('documents', 'processed_at')
    op.add_column('integrations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('integrations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('integrations', 'access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('integrations', 'connected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('integrations', 'integration_metadata')
    op.drop_column('integrations', 'is_active')
    op.drop_column('integrations', 'expires_at')
    op.drop_column('integrations', 'refresh_token')
    op.add_column('invoices', sa.Column('from_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('to_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('line_items', sa.JSON(), nullable=True))
    op.add_column('invoices', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('days_overdue', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('invoices', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('invoices', 'date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('invoices_invoice_number_key', 'invoices', type_='unique')
    op.drop_column('invoices', 'items')
    op.alter_column('team_invites', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('team_invites', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('team_invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('team_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('team_members', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('team_members', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('team_members', 'invited_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('team_members_user_id_fkey', 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'joined_at')
    op.drop_column('team_members', 'user_id')
    op.alter_column('transactions', 'document_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transactions', 'txn_type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', name='transactiontype'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('CATEGORIZED', 'UNCATEGORIZED', 'FLAGGED', 'REVIEWED', name='transactionstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('transactions', 'ml_confidence')
    op.drop_column('transactions', 'subcategory')
    op.drop_column('transactions', 'tags')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # op.add_column('transactions', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))//
    op.add_column('transactions', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('ml_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CATEGORIZED', 'UNCATEGORIZED', 'FLAGGED', 'REVIEWED', name='transactionstatus'),
               existing_nullable=True)
    op.alter_column('transactions', 'txn_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('INCOME', 'EXPENSE', name='transactiontype'),
               existing_nullable=True)
    op.alter_column('transactions', 'document_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.add_column('team_members', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('team_members', sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('team_members_user_id_fkey', 'team_members', 'users', ['user_id'], ['id'])
    op.alter_column('team_members', 'invited_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('team_members', 'owner_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('team_members', 'accepted_at')
    op.alter_column('team_invites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('team_invites', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('team_invites', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('team_invites', 'owner_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('invoices', sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint('invoices_invoice_number_key', 'invoices', ['invoice_number'])
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('invoices', 'date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('invoices', 'sent_at')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'days_overdue')
    op.drop_column('invoices', 'logo_url')
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'line_items')
    op.drop_column('invoices', 'to_address')
    op.drop_column('invoices', 'from_address')
    op.add_column('integrations', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('integration_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('integrations', 'connected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('integrations', 'access_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('integrations', 'created_at')
    op.drop_column('integrations', 'status')
    op.add_column('documents', sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('s3_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('line_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('doc_type', postgresql.ENUM('INVOICE', 'RECEIPT', 'STATEMENT', 'CONTRACT', 'OTHER', name='documenttype'), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('vendor_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('ai_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('documents', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'REVIEW', name='documentstatus'),
               existing_nullable=True)
    op.drop_column('documents', 'file_path')
    op.alter_column('budgets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('budgets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('budgets', 'alert_at_pct')
    op.drop_column('budgets', 'status')
    op.drop_column('budgets', 'percentage')
    op.drop_column('budgets', 'remaining')
    op.drop_column('budgets', 'spent')
    op.add_column('agent_logs', sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('agent_logs', sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('agent_logs', sa.Column('related_doc', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('agent_logs', sa.Column('log_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agent_logs', type_='foreignkey')
    op.create_foreign_key('agent_logs_related_doc_fkey', 'agent_logs', 'documents', ['related_doc'], ['id'])
    op.alter_column('agent_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('agent_logs', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RUNNING', 'DONE', 'FAILED', 'WAITING', name='agentstatus'),
               existing_nullable=True)
    op.alter_column('agent_logs', 'action',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('agent_logs', 'agent')
    op.drop_column('agent_logs', 'document_id')
    # ### end Alembic commands ###